from django.conf import settings
from tabmatch import Tabmatch


tb = Tabmatch(('role', 'resource', 'field', 'action', 'state', 'section'))
Row = tb.Row

PERMISSION_RULES = [
    Row('institutionmanager',   'institutions', '*', 'list', '*', '4.3.22'),
    Row('assistant',            'institutions', '*', 'list', '*', ''),
    Row('professor',            'institutions', '*', 'list', '*', '1.3.15'),
    Row('candidate',            'institutions', '*', 'list', '*', '3.3.10'),
    Row('helpdeskadmin',        'institutions', '*', 'list', '*', '5.8'),
    Row('helpdeskuser',         'institutions', '*', 'list', '*', '5.8'),
    Row('institutionmanager',   'institutions', '*', 'retrieve', '*', '4.3.22'),
    Row('assistant',            'institutions', '*', 'retrieve', '*', ''),
    Row('professor',            'institutions', '*', 'retrieve', '*', '1.3.15'),
    Row('candidate',            'institutions', '*', 'retrieve', '*', '3.3.10'),
    Row('helpdeskadmin',        'institutions', '*', 'retrieve', '*', '5.8'),
    Row('helpdeskuser',         'institutions', '*', 'retrieve', '*', '5.8'),
    Row('helpdeskadmin',        'institutions', '*', 'create', '*', '5.2.5'),
    Row('helpdeskadmin',        'institutions', '*', 'update', '*', '5.2.5'),
    Row('helpdeskadmin',        'institutions', '*', 'destroy', '*', '5.2.5'),
    Row('institutionmanager',   'institutions', 'organization', 'partial_update', 'owned', ''),
    Row('institutionmanager',   'institutions', 'regulatory_framework', 'partial_update', 'owned', ''),
    Row('institutionmanager',   'departments', '*', 'list', '*', '4.3.21'),
    Row('assistant',            'departments', '*', 'list', '*', ''),
    Row('professor',            'departments', '*', 'list', '*', '1.3.14'),
    Row('candidate',            'departments', '*', 'list', '*', ''),
    Row('helpdeskadmin',        'departments', '*', 'list', '*', '5.2.5'),
    Row('helpdeskuser',         'departments', '*', 'list', '*', '5.2.5'),
    Row('institutionmanager',   'departments', '*', 'retrieve', '*', '4.3.10'),
    Row('assistant',            'departments', '*', 'retrieve', '*', ''),
    Row('professor',            'departments', '*', 'retrieve', '*', '1.2.1'),
    Row('candidate',            'departments', '*', 'retrieve', '*', '3.3.1'),
    Row('helpdeskadmin',        'departments', '*', 'retrieve', '*', '5.2.5'),
    Row('helpdeskuser',         'departments', '*', 'retrieve', '*', '5.2.5'),
    Row('helpdeskadmin',        'departments', '*', 'create', '*', '5.2.5'),
    Row('helpdeskadmin',        'departments', '*', 'update', '*', '5.2.5'),
    Row('helpdeskadmin',        'departments', '*', 'destroy', '*', '5.2.5'),
    Row('institutionmanager',   'schools', '*', 'list', '*', '4.3.21'),
    Row('assistant',            'schools', '*', 'list', '*', ''),
    Row('professor',            'schools', '*', 'list', '*', '1.3.14'),
    Row('candidate',            'schools', '*', 'list', '*', ''),
    Row('helpdeskadmin',        'schools', '*', 'list', '*', '5.2.5'),
    Row('helpdeskuser',         'schools', '*', 'list', '*', '5.2.5'),
    Row('institutionmanager',   'schools', '*', 'retrieve', '*', '4.3.10'),
    Row('assistant',            'schools', '*', 'retrieve', '*', ''),
    Row('professor',            'schools', '*', 'retrieve', '*', '1.2.1'),
    Row('candidate',            'schools', '*', 'retrieve', '*', '3.3.1'),
    Row('helpdeskadmin',        'schools', '*', 'retrieve', '*', '5.2.5'),
    Row('helpdeskuser',         'schools', '*', 'retrieve', '*', '5.2.5'),
    Row('helpdeskadmin',        'schools', '*', 'create', '*', '5.2.5'),
    Row('helpdeskadmin',        'schools', '*', 'update', '*', '5.2.5'),
    Row('helpdeskadmin',        'schools', '*', 'destroy', '*', '5.2.5'),
    Row('institutionmanager',   'subject-areas', '*', 'list', '*', '4.3.10'),
    Row('assistant',            'subject-areas', '*', 'list', '*', ''),
    Row('professor',            'subject-areas', '*', 'list', '*', '3.3.1'),
    Row('candidate',            'subject-areas', '*', 'list', '*', '3.3.1'),
    Row('helpdeskadmin',        'subject-areas', '*', 'list', '*', ''),
    Row('helpdeskuser',         'subject-areas', '*', 'list', '*', ''),
    Row('institutionmanager',   'subject-areas', '*', 'retrieve', '*', '4.3.10'),
    Row('assistant',            'subject-areas', '*', 'retrieve', '*', ''),
    Row('professor',            'subject-areas', '*', 'retrieve', '*', '1.3.3'),
    Row('candidate',            'subject-areas', '*', 'retrieve', '*', '3.3.2'),
    Row('helpdeskadmin',        'subject-areas', '*', 'retrieve', '*', ''),
    Row('helpdeskuser',         'subject-areas', '*', 'retrieve', '*', ''),
    Row('helpdeskadmin',        'subject-areas', '*', 'create', '*', ''),
    Row('helpdeskadmin',        'subject-areas', '*', 'update', '*', ''),
    Row('helpdeskadmin',        'subject-areas', '*', 'destroy', '*', ''),
    Row('institutionmanager',   'subjects', '*', 'list', '*', '4.3.10'),
    Row('assistant',            'subjects', '*', 'list', '*', ''),
    Row('professor',            'subjects', '*', 'list', '*', '3.3.1'),
    Row('candidate',            'subjects', '*', 'list', '*', '3.3.1'),
    Row('helpdeskadmin',        'subjects', '*', 'list', '*', ''),
    Row('helpdeskuser',         'subjects', '*', 'list', '*', ''),
    Row('institutionmanager',   'subjects', '*', 'retrieve', '*', '4.3.10'),
    Row('assistant',            'subjects', '*', 'retrieve', '*', ''),
    Row('professor',            'subjects', '*', 'retrieve', '*', '1.3.3'),
    Row('candidate',            'subjects', '*', 'retrieve', '*', '3.3.2'),
    Row('helpdeskadmin',        'subjects', '*', 'retrieve', '*', ''),
    Row('helpdeskuser',         'subjects', '*', 'retrieve', '*', ''),
    Row('helpdeskadmin',        'subjects', '*', 'create', '*', ''),
    Row('helpdeskadmin',        'subjects', '*', 'update', '*', ''),
    Row('helpdeskadmin',        'subjects', '*', 'destroy', '*', ''),
    Row('institutionmanager',   'positions', '*', 'list', '*', '4.3.9'),
    Row('assistant',            'positions', '*', 'list', '*', ''),
    Row('professor',            'positions', '*', 'list', '*', '3.3.2'),
    Row('candidate',            'positions', '*', 'list', '*', '3.3.2'),
    Row('helpdeskadmin',        'positions', '*', 'list', '*', '5.13'),
    Row('helpdeskuser',         'positions', '*', 'list', '*', '5.13'),
    Row('institutionmanager',   'positions', '*', 'retrieve', 'owned', '4.3.9'),
    Row('assistant',            'positions', '*', 'retrieve', 'owned', ''),
    Row('professor',            'positions', '*', 'retrieve', 'open', '1.3'),
    Row('professor',            'positions', '*', 'retrieve', 'participates', '1.3'),
    Row('candidate',            'positions', '*', 'retrieve', 'open', '3.3.4'),
    Row('helpdeskadmin',        'positions', '*', 'retrieve', '*', '5.14'),
    Row('helpdeskuser',         'positions', '*', 'retrieve', '*', '5.14'),
    Row('institutionmanager',   'positions', '*', 'create', '*', '4.3.10'),
    Row('institutionmanager',   'positions', 'state', 'partial_update', 'before_open', '4.3.11.b'),
    Row('institutionmanager',   'positions', 'state', 'partial_update', 'electing', '4.3.11.g'),
    Row('institutionmanager',   'positions', 'state', 'partial_update', 'electing', '4.3.11.h'),
    Row('institutionmanager',   'positions', 'starts_at', 'partial_update', 'before_open', '4.3.11.c'),
    Row('helpdeskadmin',        'positions', 'starts_at', 'partial_update', '*', '5.2.4'),
    Row('institutionmanager',   'positions', 'ends_at', 'partial_update', 'before_open', '4.3.11.c'),
    Row('helpdeskadmin',        'positions', 'ends_at', 'partial_update', '*', '5.2.4'),
    Row('institutionmanager',   'positions', 'electors', 'partial_update', 'closed, decision_to_form_electors_file', '4.3.14'),
    Row('institutionmanager',   'positions', 'committee', 'partial_update', 'electing, check_electors_completed, electors_meeting_closed', '4.3.15'),
    Row('institutionmanager',   'positions', 'elected', 'partial_update', 'electing, committee_meeting', '4.3.11.f'),
    Row('institutionmanager',   'registries', '*', 'list', '*', '4.3.1'),
    Row('professor',            'registries', '*', 'list', '*', '1.3.14'),
    Row('candidate',            'registries', '*', 'list', '*', '3.3.9'),
    Row('helpdeskadmin',        'registries', '*', 'list', '*', '5.1.9'),
    Row('helpdeskuser',         'registries', '*', 'list', '*', '5.1.9'),
    Row('institutionmanager',   'registries', '*', 'retrieve', '*', '4.3.1'),
    Row('professor',            'registries', '*', 'retrieve', '*', '1.3.14'),
    Row('candidate',            'registries', '*', 'retrieve', '*', '3.3.9'),
    Row('helpdeskadmin',        'registries', '*', 'retrieve', '*', '5.1.9'),
    Row('helpdeskuser',         'registries', '*', 'retrieve', '*', '5.1.9'),
    Row('institutionmanager',   'registries', '*', 'create', '*', '4.3.3'),
    Row('institutionmanager',   'registries', 'members', 'partial_update', 'owned', '4.3.6'),
    Row('institutionmanager',   'candidacies', '*', 'list', 'owned', '4.3.16'),
    Row('assistant',            'candidacies', '*', 'list', 'owned', '4.3.16'),
    Row('professors',           'candidacies', '*', 'list', 'owned, participates, others_can_view', '1.3.3'),
    Row('professors',           'candidacies', 'candidate', 'list', 'owned', '1.3.3'),
    Row('candidate',            'candidacies', '*', 'list', 'owned, others_can_view', '3.3.5'),
    Row('candidate',            'candidacies', 'candidate', 'list', 'owned', '3.3.5'),
    Row('helpdeskadmin',        'candidacies', '*', 'list', '*', '5.16'),
    Row('helpdeskuser',         'candidacies', '*', 'list', '*', '5.16'),
    Row('institutionmanager',   'candidacies', '*', 'retrieve', 'owned', '4.3.16'),
    Row('assistant',            'candidacies', '*', 'retrieve', 'owned', '4.3.16'),
    Row('professors',           'candidacies', '*', 'retrieve', 'owned, participates, others_can_view', '1.3.5'),
    Row('professors',           'candidacies', 'candidate', 'retrieve', 'owned', '1.3.3'),
    Row('candidate',            'candidacies', '*', 'retrieve', 'owned, others_can_view', '3.3.5'),
    Row('candidate',            'candidacies', 'candidate', 'retrieve', 'owned', '3.3.5'),
    Row('helpdeskadmin',        'candidacies', '*', 'retrieve', '*', '5.17'),
    Row('helpdeskuser',         'candidacies', '*', 'retrieve', '*', '5.17'),
    Row('professors',           'candidacies', '*', 'create', 'open', '1.3.9'),
    Row('candidate',            'candidacies', '*', 'create', 'open', '3.3.3'),
    Row('professors',           'candidacies', 'files', 'partial_update', 'owned, open', '1.3.12'),
    Row('candidate',            'candidacies', 'files', 'partial_update', 'owned, open', '3.3.6'),
    Row('professors',           'candidacies', '*', 'destroy', 'owned, open', '1.3.13'),
    Row('candidate',            'candidacies', '*', 'destroy', 'owned, open', '3.3.7'),
    Row('helpdeskadmin',        'candidacies', 'active', 'partial_update', 'after_closed, electors_meeting_open', '5.2.3.a'),
    Row('institutionmanager',   'assistants', '*', 'list', 'owned', '4.3.7'),
    Row('helpdeskadmin',        'assistants', '*', 'list', '*', '5.1.2'),
    Row('helpdeskuser',         'assistants', '*', 'list', '*', '5.1.2'),
    Row('helpdeskadmin',        'assistants', '*', 'retrieve', '*', '5.1.2'),
    Row('helpdeskuser',         'assistants', '*', 'retrieve', '*', '5.1.2'),
    Row('institutionmanager',   'assistants', '*', 'retrieve', 'owned', '4.3.7'),
    Row('institutionmanager',   'assistants', '*', 'create', '*', '4.3.7'),
    Row('institutionmanager',   'assistants', 'user.is_active', 'partial_update', 'owned', '4.3.7'),
    Row('institutionmanager',   'assistants', 'user.profile', 'partial_update', 'owned', '4.3.7'),
    Row('helpdeskadmin',        'professors', '*', 'list', '*', '5.1.2'),
    Row('helpdeskuser',         'professors', '*', 'list', '*', '5.1.2'),
    Row('helpdeskadmin',        'professors', '*', 'retrieve', '*', '5.1.3'),
    Row('helpdeskuser',         'professors', '*', 'retrieve', '*', '5.1.3'),
    Row('helpdeskadmin',        'professors', 'user.is_active', 'partial_update', '*', '5.1.4'),
    Row('helpdeskadmin',        'professors', 'user.is_certified', 'partial_update', '*', '5.1.5'),
    Row('helpdeskadmin',        'professors', 'selected_fields', 'partial_update', '*', '5.1.3'),
    Row('helpdeskadmin',        'candidates', '*', 'list', '*', '5.1.2'),
    Row('helpdeskuser',         'candidates', '*', 'list', '*', '5.1.2'),
    Row('helpdeskadmin',        'candidates', '*', 'retrieve', '*', '5.1.3'),
    Row('helpdeskuser',         'candidates', '*', 'retrieve', '*', '5.1.3'),
    Row('helpdeskadmin',        'candidates', 'user.is_active', 'partial_update', '*', '5.1.4'),
    Row('helpdeskadmin',        'candidates', 'user.is_certified', 'partial_update', '*', '5.1.5'),
    Row('helpdeskadmin',        'candidates', 'selected_fields', 'partial_update', '*', '5.1.3'),
    Row('helpdeskadmin',        'helpdeskusers', '*', 'list', '*', ''),
    Row('helpdeskadmin',        'helpdeskusers', '*', 'retrieve', '*', ''),
    Row('helpdeskadmin',        'helpdeskusers', '*', 'create', '*', ''),
    Row('helpdeskadmin',        'helpdeskusers', 'user.email', 'partial_update', '*', ''),
    Row('helpdeskadmin',        'helpdeskusers', 'user.el', 'partial_update', '*', ''),
    Row('helpdeskadmin',        'helpdeskusers', 'user.en', 'partial_update', '*', ''),
    Row('helpdeskadmin',        'institution-managers', '*', 'create', '*', ''),
    Row('helpdeskadmin',        'professors', '*', 'create', '*', ''),
    Row('helpdeskadmin',        'candidates', '*', 'create', '*', ''),
]

tb.update(PERMISSION_RULES)
