PERMISSION_RULES = {
    'institutions': {
        ('institutionmanager', '*', 'list', '*', '4.3.22'),
        ('assistant', '*', 'list', '*', ''),
        ('professor', '*', 'list', '*', '1.3.15'),
        ('candidate', '*', 'list', '*', '3.3.10'),
        ('helpdeskadmin', '*', 'list', '*', '5.8'),
        ('helpdeskuser', '*', 'list', '*', '5.8'),
        ('institutionmanager', '*', 'retrieve', '*', '4.3.22'),
        ('assistant', '*', 'retrieve', '*', ''),
        ('professor', '*', 'retrieve', '*', '1.3.15'),
        ('candidate', '*', 'retrieve', '*', '3.3.10'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.8'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.8'),
        ('helpdeskadmin', '*', 'create', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'update', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'partial_update', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'destroy', '*', '5.2.5'),
        ('institutionmanager', 'organization', 'partial_update', 'owned', ''),
        ('institutionmanager', 'regulatory_framework', 'partial_update',
            'owned', '')
    },
    'departments': {
        ('institutionmanager', '*', 'list', '*', '4.3.21'),
        ('assistant', '*', 'list', '*', ''),
        ('professor', '*', 'list', '*', '1.3.14'),
        ('candidate', '*', 'list', '*', ''),
        ('helpdeskadmin', '*', 'list', '*', '5.2.5'),
        ('helpdeskuser', '*', 'list', '*', '5.2.5'),
        ('institutionmanager', '*', 'retrieve', '*', '4.3.10'),
        ('assistant', '*', 'retrieve', '*', ''),
        ('professor', '*', 'retrieve', '*', '1.2.1'),
        ('candidate', '*', 'retrieve', '*', '3.3.1'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.2.5'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'create', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'update', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'partial_update', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'destroy', '*', '5.2.5')
    },
    'schools': {
        ('institutionmanager', '*', 'list', '*', '4.3.21'),
        ('assistant', '*', 'list', '*', ''),
        ('professor', '*', 'list', '*', '1.3.14'),
        ('candidate', '*', 'list', '*', ''),
        ('helpdeskadmin', '*', 'list', '*', '5.2.5'),
        ('helpdeskuser', '*', 'list', '*', '5.2.5'),
        ('institutionmanager', '*', 'retrieve', '*', '4.3.10'),
        ('assistant', '*', 'retrieve', '*', ''),
        ('professor', '*', 'retrieve', '*', '1.2.1'),
        ('candidate', '*', 'retrieve', '*', '3.3.1'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.2.5'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'create', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'update', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'partial_update', '*', '5.2.5'),
        ('helpdeskadmin', '*', 'destroy', '*', '5.2.5'),
    },
    'subject-areas': {
        ('institutionmanager', '*', 'list', '*', '4.3.10'),
        ('assistant', '*', 'list', '*', ''),
        ('professor', '*', 'list', '*', '3.3.1'),
        ('candidate', '*', 'list', '*', '3.3.1'),
        ('helpdeskadmin', '*', 'list', '*', ''),
        ('helpdeskuser', '*', 'list', '*', ''),
        ('institutionmanager', '*', 'retrieve', '*', '4.3.10'),
        ('assistant', '*', 'retrieve', '*', ''),
        ('professor', '*', 'retrieve', '*', '1.3.3'),
        ('candidate', '*', 'retrieve', '*', '3.3.2'),
        ('helpdeskadmin', '*', 'retrieve', '*', ''),
        ('helpdeskuser', '*', 'retrieve', '*', ''),
        ('helpdeskadmin', '*', 'create', '*', ''),
        ('helpdeskadmin', '*', 'update', '*', ''),
        ('helpdeskadmin', '*', 'destroy', '*', ''),
    },
    'subjects': {
        ('institutionmanager', '*', 'list', '*', '4.3.10'),
        ('assistant', '*', 'list', '*', ''),
        ('professor', '*', 'list', '*', '3.3.1'),
        ('candidate', '*', 'list', '*', '3.3.1'),
        ('helpdeskadmin', '*', 'list', '*', ''),
        ('helpdeskuser', '*', 'list', '*', ''),
        ('institutionmanager', '*', 'retrieve', '*', '4.3.10'),
        ('assistant', '*', 'retrieve', '*', ''),
        ('professor', '*', 'retrieve', '*', '1.3.3'),
        ('candidate', '*', 'retrieve', '*', '3.3.2'),
        ('helpdeskadmin', '*', 'retrieve', '*', ''),
        ('helpdeskuser', '*', 'retrieve', '*', ''),
        ('helpdeskadmin', '*', 'create', '*', ''),
        ('helpdeskadmin', '*', 'update', '*', ''),
        ('helpdeskadmin', '*', 'destroy', '*', ''),
    },
    'positions': {
        ('institutionmanager', '*', 'list', '*', '4.3.9'),
        ('assistant', '*', 'list', '*', ''),
        ('professor', '*', 'list', '*', '3.3.2'),
        ('candidate', '*', 'list', '*', '3.3.2'),
        ('helpdeskadmin', '*', 'list', '*', '5.13'),
        ('helpdeskuser', '*', 'list', '*', '5.13'),
        ('institutionmanager', '*', 'retrieve', 'owned', '4.3.9'),
        ('assistant', '*', 'retrieve', 'owned', ''),
        ('professor', '*', 'retrieve', 'open', '1.3'),
        ('professor', '*', 'retrieve', 'participates', '1.3'),
        ('candidate', '*', 'retrieve', 'open', '3.3.4'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.14'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.14'),
        ('institutionmanager', '*', 'create', '*', '4.3.10'),
        ('institutionmanager', 'state', 'partial_update',
            'before_open', '4.3.11.b'),
        ('institutionmanager', 'state', 'partial_update', 'electing',
            '4.3.11.g'),
        ('institutionmanager', 'state', 'partial_update', 'electing',
            '4.3.11.h'),
        ('institutionmanager', 'starts_at', 'partial_update',
            'before_open', '4.3.11.c'),
        ('helpdeskadmin', 'starts_at', 'partial_update', '*', '5.2.4'),
        ('institutionmanager', 'ends_at', 'partial_update',
            'before_open', '4.3.11.c'),
        ('helpdeskadmin', 'ends_at', 'partial_update', '*', '5.2.4'),
        ('institutionmanager', 'electors', 'partial_update',
            'closed, decision_to_form_electors_file', '4.3.14'),
        ('institutionmanager', 'committee', 'partial_update',
            'electing, check_electors_completed, electors_meeting_closed',
            '4.3.15'),
        ('institutionmanager', 'elected', 'partial_update',
            'electing, committee_meeting', '4.3.11.f'),
    },
    'registries': {
        ('institutionmanager', '*', 'list', '*', '4.3.1'),
        ('professor', '*', 'list', '*', '1.3.14'),
        ('candidate', '*', 'list', '*', '3.3.9'),
        ('helpdeskadmin', '*', 'list', '*', '5.1.9'),
        ('helpdeskuser', '*', 'list', '*', '5.1.9'),
        ('institutionmanager', '*', 'retrieve', '*', '4.3.1'),
        ('professor', '*', 'retrieve', '*', '1.3.14'),
        ('candidate', '*', 'retrieve', '*', '3.3.9'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.1.9'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.1.9'),
        ('institutionmanager', '*', 'create', '*', '4.3.3'),
        ('institutionmanager', 'members', 'partial_update', 'owned', '4.3.6'),
    },
    'candidacies': {
        ('institutionmanager', '*', 'list', 'owned', '4.3.16'),
        ('assistant', '*', 'list', 'owned', '4.3.16'),
        ('professors', '*', 'list', 'owned, participates, others_can_view',
            '1.3.3'),
        ('professors', 'candidate', 'list', 'owned', '1.3.3'),
        ('candidate', '*', 'list', 'owned, others_can_view', '3.3.5'),
        ('candidate', 'candidate', 'list', 'owned', '3.3.5'),
        ('helpdeskadmin', '*', 'list', '*', '5.16'),
        ('helpdeskuser', '*', 'list', '*', '5.16'),
        ('institutionmanager', '*', 'retrieve', 'owned', '4.3.16'),
        ('assistant', '*', 'retrieve', 'owned', '4.3.16'),
        ('professors', '*', 'retrieve', 'owned, participates,
            others_can_view', '1.3.5'),
        ('professors', 'candidate', 'retrieve', 'owned', '1.3.3'),
        ('candidate', '*', 'retrieve', 'owned, others_can_view', '3.3.5'),
        ('candidate', 'candidate', 'retrieve', 'owned', '3.3.5'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.17'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.17'),
        ('professors', '*', 'create', 'open', '1.3.9'),
        ('candidate', '*', 'create', 'open', '3.3.3'),
        ('professors', 'files', 'partial_update', 'owned, open', '1.3.12'),
        ('candidate', 'files', 'partial_update', 'owned, open', '3.3.6'),
        ('professors', '*', 'destroy', 'owned, open', '1.3.13'),
        ('candidate', '*', 'destroy', 'owned, open', '3.3.7'),
        ('helpdeskadmin', 'active', 'partial_update',
            'after_closed, electors_meeting_open', '5.2.3.a'),
    },
    'assistants': {
        ('institutionmanager', '*', 'list', 'owned', '4.3.7'),
        ('helpdeskadmin', '*', 'list', '*', '5.1.2'),
        ('helpdeskuser', '*', 'list', '*', '5.1.2'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.1.2'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.1.2'),
        ('institutionmanager', '*', 'retrieve', 'owned', '4.3.7'),
        ('institutionmanager', '*', 'create', '*', '4.3.7'),
        ('institutionmanager', 'user.is_active', 'partial_update',
            'owned', '4.3.7'),
        ('institutionmanager', 'user.profile', 'partial_update',
            'owned', '4.3.7'),
    },
    'professors': {
        ('helpdeskadmin', '*', 'list', '*', '5.1.2'),
        ('helpdeskuser', '*', 'list', '*', '5.1.2'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.1.3'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.1.3'),
        ('helpdeskadmin', '*', 'partial_update', '*', '5.1.5'),
        ('helpdeskadmin', '*', 'create', '*', ''),
    },
    'candidates': {
        ('helpdeskadmin', '*', 'list', '*', '5.1.2'),
        ('helpdeskuser', '*', 'list', '*', '5.1.2'),
        ('helpdeskadmin', '*', 'retrieve', '*', '5.1.3'),
        ('helpdeskuser', '*', 'retrieve', '*', '5.1.3'),
        ('helpdeskadmin', '*', 'partial_update', '*', '5.1.3'),
        ('helpdeskadmin', '*', 'create', '*', ''),
    },
    'helpdeskusers': {
        ('helpdeskadmin', '*', 'list', '*', ''),
        ('helpdeskadmin', '*', 'retrieve', '*', ''),
        ('helpdeskadmin', '*', 'create', '*', ''),
        ('helpdeskadmin', 'user.email', 'partial_update', '*', ''),
        ('helpdeskadmin', 'user.el', 'partial_update', '*', ''),
        ('helpdeskadmin', 'user.en', 'partial_update', '*', ''),
    },
    'institution-managers': {
        ('helpdeskadmin', '*', 'create', '*', ''),
        ('helpdeskadmin', '*', 'partial_update', '*', ''),
    }
}
