
"""
Role, Resource, Fields, Operation, State, Spec number
"""
PERMISSIONS = [
    ('institutionmanager',    'institutions', '*', 'list', '*', '4.3.22'),
    ('professor',             'institutions', '*', 'list', '*', '1.3.15'),
    ('candidate',             'institutions', '*', 'list', '*', '3.3.10'),
    ('helpdeskadmin',         'institutions', '*', 'list', '*', '5.8'),
    ('helpdeskuser',          'institutions', '*', 'list', '*', '5.8'),
    ('institutionmanager',    'institutions', '*', 'retrieve', '*', '4.3.22'),
    ('professor',             'institutions', '*', 'retrieve', '*', '1.3.15'),
    ('candidate',             'institutions', '*', 'retrieve', '*', '3.3.10'),
    ('helpdeskadmin',         'institutions', '*', 'retrieve', '*', '5.8'),
    ('helpdeskuser',          'institutions', '*', 'retrieve', '*', '5.8'),
    ('helpdeskadmin',         'institutions', '*', 'create', '*', '5.2.5'),
    ('helpdeskadmin',         'institutions', '*', 'update', '*', '5.2.5'),
    ('helpdeskadmin',         'institutions', '*', 'destroy', '*', '5.2.5'),
    ('institutionmanager',    'institutions', 'organization', 'partial_update', 'owned', None),
    ('institutionmanager',    'institutions', 'regulatory_framework', 'partial_update', 'owned', None),

    ('institutionmanager',    'departments', '*', 'list', '*', '4.3.21'),
    ('professor',             'departments', '*', 'list', '*', '1.3.14'),
    ('candidate',             'departments', '*', 'list', '*', ''),
    ('helpdeskadmin',         'departments', '*', 'list', '*', '5.2.5'),
    ('helpdeskuser',          'departments', '*', 'list', '*', '5.2.5'),
    ('institutionmanager',    'departments', '*', 'retrieve', '*', '4.3.10'),
    ('professor',             'departments', '*', 'retrieve', '*', '1.2.1'),
    ('candidate',             'departments', '*', 'retrieve', '*', '3.3.1'),
    ('helpdeskadmin',         'departments', '*', 'retrieve', '*', '5.2.5'),
    ('helpdeskuser',          'departments', '*', 'retrieve', '*', '5.2.5'),
    ('helpdeskadmin',         'departments', '*', 'create', '*', '5.2.5'),
    ('helpdeskadmin',         'departments', '*', 'update', '*', '5.2.5'),
    ('helpdeskadmin',         'departments', '*', 'destroy', '*', '5.2.5'),

    ('institutionmanager',    'subjects-areas', '*', 'list', '*', '4.3.10'),
    ('professor',             'subjects-areas', '*', 'list', '*', '3.3.1'),
    ('candidate',             'subjects-areas', '*', 'list', '*', '3.3.1'),
    ('helpdeskadmin',         'subjects-areas', '*', 'list', '*', None),
    ('helpdeskuser',          'subjects-areas', '*', 'list', '*', None),
    ('institutionmanager',    'subjects-areas', '*', 'retrieve', '*', '4.3.10'),
    ('professor',             'subjects-areas', '*', 'retrieve', '*', '1.3.3'),
    ('candidate',             'subjects-areas', '*', 'retrieve', '*', '3.3.2'),
    ('helpdeskadmin',         'subjects-areas', '*', 'retrieve', '*', None),
    ('helpdeskuser',          'subjects-areas', '*', 'retrieve', '*', None),
    ('helpdeskadmin',         'subjects-areas', '*', 'create', '*', None),
    ('helpdeskadmin',         'subjects-areas', '*', 'update', '*', None),
    ('helpdeskadmin',         'subjects-areas', '*', 'destroy', '*', None),
    ('institutionmanager',    'subjects', '*', 'list', '*', '4.3.10'),
    ('professor',             'subjects', '*', 'list', '*', '3.3.1'),
    ('candidate',             'subjects', '*', 'list', '*', '3.3.1'),
    ('helpdeskadmin',         'subjects', '*', 'list', '*', None),
    ('helpdeskuser',          'subjects', '*', 'list', '*', None),
    ('institutionmanager',    'subjects', '*', 'retrieve', '*', '4.3.10'),
    ('professor',             'subjects', '*', 'retrieve', '*', '1.3.3'),
    ('candidate',             'subjects', '*', 'retrieve', '*', '3.3.2'),
    ('helpdeskadmin',         'subjects', '*', 'retrieve', '*', None),
    ('helpdeskuser',          'subjects', '*', 'retrieve', '*', None),
    ('helpdeskadmin',         'subjects', '*', 'create', '*', None),
    ('helpdeskadmin',         'subjects', '*', 'update', '*', None),
    ('helpdeskadmin',         'subjects', '*', 'destroy', '*', None),

    ('institutionmanager',    'positions', '*', 'list', 'owned', '4.3.9'),
    ('professor',             'positions', '*', 'list', '*', '3.3.2'),
    ('candidate',             'positions', '*', 'list', '*', '3.3.2'),
    ('helpdeskadmin',         'positions', '*', 'list', '*', '5.13'),
    ('helpdeskuser',          'positions', '*', 'list', '*', '5.13'),
    ('institutionmanager',    'positions', '*', 'retrieve', 'owned', '4.3.9'),
    ('professor',             'positions', '*', 'retrieve', '*', '1.3'),
    ('candidate',             'positions', '*', 'retrieve', '*', '3.3.4'),
    ('helpdeskadmin',         'positions', '*', 'retrieve', '*', '5.14'),
    ('helpdeskuser',          'positions', '*', 'retrieve', '*', '5.14'),
    ('institutionmanager',    'positions', '*', 'create', '*', '4.3.10'),
    ('institutionmanager',    'positions', 'state', 'partial_update', 'before_open', '4.3.11.b'),
    ('institutionmanager',    'positions', 'state', 'partial_update', 'electing', '4.3.11.g'),
    ('institutionmanager',    'positions', 'state', 'partial_update', 'electing', '4.3.11.h'),
    ('institutionmanager',    'positions', 'starts_at', 'partial_update', 'before_open', '4.3.11.c'),
    ('institutionmanager',    'positions', 'ends_at', 'partial_update', 'before_open', '4.3.11.c'),
    ('institutionmanager',    'positions', 'electors', 'partial_update', 'closed, decision_to_form_electors_file', '4.3.14'),
    ('institutionmanager',    'positions', 'committee', 'partial_update', 'electing, check_electors_completed, electors_meeting', '4.3.15'),
    ('institutionmanager',    'positions', 'elected', 'partial_update', 'electing, committee_meeting', '4.3.11.f'),

]
