# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 13:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('father_name', models.CharField(max_length=30)),
                ('first_name_latin', models.CharField(blank=True, max_length=30)),
                ('last_name_latin', models.CharField(blank=True, max_length=30)),
                ('father_name_latin', models.CharField(blank=True, max_length=30)),
                ('id_passport', models.CharField(help_text='ID or passport', max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DomesticProfessor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.CharField(choices=[('A', 'Professor'), ('B', 'Assistant')], default='B', max_length=1)),
                ('no_cv_url', models.BooleanField()),
                ('cv_url', models.URLField(blank=True)),
                ('cv', models.FileField(upload_to='uploads/')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('has_accepted_terms', models.BooleanField()),
                ('institute', models.CharField(max_length=30)),
                ('fek', models.CharField(max_length=255)),
                ('fek_file', models.FileField(upload_to='uploads/')),
                ('no_fek_subject', models.BooleanField()),
                ('fek_subject', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('apella.userprofile', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ForeignProfessor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.CharField(choices=[('A', 'Professor'), ('B', 'Assistant')], default='B', max_length=1)),
                ('no_cv_url', models.BooleanField()),
                ('cv_url', models.URLField(blank=True)),
                ('cv', models.FileField(upload_to='uploads/')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('has_accepted_terms', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('apella.userprofile', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
