# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApellaAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'Superadmin'), ('1', 'Helpdesk'), ('2', 'Ministry')], default='1', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('A', 'Professor'), ('B', 'Assistant')], default='B', max_length=1)),
                ('no_cv_url', models.BooleanField()),
                ('cv_url', models.URLField(blank=True)),
                ('cv', models.FileField(blank=True, upload_to='uploads/')),
                ('discipline', models.CharField(blank=True, max_length=255)),
                ('has_accepted_terms', models.BooleanField(default=False)),
                ('institution', models.CharField(max_length=30)),
                ('fek', models.CharField(max_length=255)),
                ('fek_file', models.FileField(blank=True, upload_to='uploads/')),
                ('no_fek_subject', models.BooleanField()),
                ('fek_subject', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeignProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('A', 'Professor'), ('B', 'Assistant')], default='B', max_length=1)),
                ('no_cv_url', models.BooleanField()),
                ('cv_url', models.URLField(blank=True)),
                ('cv', models.FileField(blank=True, upload_to='uploads/')),
                ('discipline', models.CharField(blank=True, max_length=255)),
                ('has_accepted_terms', models.BooleanField(default=False)),
                ('country', models.CharField(choices=[('GR', 'Greece'), ('FR', 'France')], default='FR', max_length=2)),
                ('speaks_greek', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=30)),
                ('authority', models.CharField(choices=[('1', 'Dean'), ('2', 'President')], default='1', max_length=1)),
                ('authority_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('0', 'Admin'), ('1', 'Substitute'), ('2', 'Helper')], default='1', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
